import "@/app/_styles/globals.css"
import Header from "@/app/_components/Header";
import Navigation from "@/app/_components/Navigation";

export const metadata = {
  title: 'The Wild Oasis',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-gray-100 min-h-screen">
      <Header />
      <Navigation />
      <div>
      <main>
          {children}
      </main>
      </div>
      </body>
    </html>
  )
}
